### ISSUE TITLE
Suddenly more coverage?

### ISSUE THREAD

**Issue by larsgw** [larsgw/citation.js#149]
Somehow, in two commits updating completely unrelated files, [the coverage had a `+5.08%` uptick](https://codecov.io/gh/larsgw/citation.js/compare/02db8a96ca2325721b720ef8804bf853af1ec777...f4dcd5294909c46ce3009665e56c1cf5ffcf1130), which tells me they aren't completely unrelated. However, the only related thing I can imagine right now is moving the babel config (401de3e2b38219411b6ab86f8a4d0a853c78e28b).

**Comment by loganfsmyth** [comment]
Pinged you on Slack but posting here in case anyone else comes across this. This was happening because of there was a bug in `babel.config.js` support that was fixed in https://github.com/babel/babel/issues/7922, but this project is still using the version that does not include that fix.

**Comment by larsgw** [comment]
Thanks! Fixed in ea89c64b2051c7861b313c2dbe7428a5861dae0a.
