### ISSUE TITLE
Correctly convert rich text formatting in CSL JSON

### ISSUE THREAD

**Issue by rmzelle** [larsgw/citation.js#150]
A ref-extractor user reported an issue with the CSL JSON to BibTeX conversion, regarding the rich text in-field markup that is typically used in CSL JSON: https://github.com/rmzelle/ref-extractor/issues/25

The markup syntax is described at http://docs.citationstyles.org/en/1.0-20100321/release-notes.html#rich-text-markup-within-fields and https://www.zotero.org/support/kb/rich_text_bibliography.

**Comment by larsgw** [comment]
Sorry, I've been AFK for a while. I'll see what I can do.

**Comment by larsgw** [comment]
Should be fixed in `v0.4.0-9`.
