### ISSUE TITLE
'url' prop in getBibTeXJSON and parseBibTeXJSON are inconsistent

### ISSUE THREAD

**Issue by mydu** [larsgw/citation.js#153]
Uppercase for `parseBibTeXJSON` and lowercase for `getBibTeXJSON`

**Comment by larsgw** [comment]
Thanks for reporting this, by the way. I'll create a back-port release.

**Comment by larsgw** [comment]
[`0.4.0-6`](https://www.npmjs.com/package/citation-js/v/0.4.0-6) should work now.
