### ISSUE TITLE
BibTeX capitalisation and CSL nocase

### ISSUE THREAD

**Issue by larsgw** [larsgw/citation.js#155]
When working with BibTeX input, titles fields are sometimes entirely wrapped in an extra pair of brackets, e.g.

    title = {{foo}}

Should this result in the whole title being wrapped in `<span class="nocase">...</span>`, as per https://www.zotero.org/support/kb/rich_text_bibliography?

Moreover, should BibTeX output automatically have an extra `{...}` wrapping title fields, which is what happens now?

@rmzelle: Thoughts?

**Comment by rmzelle** [comment]
Sorry, I don't know anything about the BibTeX format. @adam3smith, do you know who is our residential expert? Emilio or Karnesky?

**Comment by retorquere** [comment]
If you're importing {{...}}, that should in principle translate to a nocase wrap. I don't do this in BBT though.

BibTeX output should absolutely not automatically be wrapped in an extra pair of braces. I see this recommendation occasionally but it's simply wrong. There are bibtex styles that demand legitimately that they can do their own case folding, and the second pair of braces prevents this. There is an unfortunate difference in baseline assumptions about how titles should be written in Zotero (sentence case) and bibtex (Title Case) that cannot just be ignored.

**Comment by retorquere** [comment]
Some of the madness of brace protection and caps meddling is documented [here](https://retorque.re/zotero-better-bibtex/faq/). It's not an easy subject with a few subtle edge cases.

**Comment by retorquere** [comment]
BTW if the concern is parsing (for later processing), the parser BBT uses has been split off and now lives [here](https://github.com/fiduswriter/biblatex-csl-converter).

**Comment by retorquere** [comment]
It doesn't need to be, a single brace will most of the time, [just not always](https://retorque.re/zotero-better-bibtex/faq/#why-the-double-braces) work. `{{` always works. A lot of people (me included) prefer `{...}` for the looks, but deciding algorithmically when `{...}` will work was more work than I was willing to do.

If you're looking for bib(la)tex test cases BTW, [have at it](https://github.com/retorquere/zotero-better-bibtex/tree/master/test/fixtures/import).

**Comment by retorquere** [comment]
> I kept the translation between span class="nocase" and {...} for now, both importing and exporting. Now that I read the FAQ perhaps that should be {{...}}?

This argument only goes for exporting BTW. Most of the refs for import you will find will not use `{{...}}`. You're braver than me if you want to parse that fully as bibtex/biblatex intends it (even ignoring the differences between them), but translating `{...}` into `<span class="nocase">...</span>` (which I don't) is in principle the right thing to do.

**Comment by larsgw** [comment]
Then I'll leave the behaviour like this (for now at least, maybe I'll think differently about it tomorrow). Thanks a lot for the help!

> If you're looking for bib(la)tex test cases BTW, have at it.

Thanks, I'll definitely take a look at that.
