### ISSUE TITLE
`Cite.plugins.output.config` is undefined

### ISSUE THREAD

**Issue by jczerwinski** [larsgw/citation.js#161]
I'm trying to import a new CSL style.

According to the docs (https://citation.js.org/api/tutorial-output_plugins_csl.html), we should be able to do:

```js
let config = Cite.plugins.output.config.get('csl');
config.templates.add(citation_style_name, citation_stylesheet);
```
But `Cite.plugins.output.config` is undefined :(

Did the API change and the docs are just out of date? Or something else?

Cheers!

**Comment by jczerwinski** [comment]
For google's sake, the error message is:

`TypeError: Cannot read property 'get' of undefined`

**Comment by jczerwinski** [comment]
I'm using `"citation-js": "^0.4.0-9"`

**Comment by jczerwinski** [comment]
Looks like this is the new API:

```js
Citation.CSL.register.addTemplate(citation_style_name, citation_stylesheet);
```

**Comment by larsgw** [comment]
No, that's the old API. The docs contain a typo, it should simply be `Cite.plugins.config.get('csl')`. Sorry for the confusion.

**Comment by jczerwinski** [comment]
No worries, and thanks for your help. I still can't seem to get it working, unfortunately.

Neither of the above methods for registering a style throw an error; however, when I try to format a citation or bibliography using said style, it doesn't seem to work, and just silently defaults back to `apa`. The built in styles do all work, though.

Can you confirm that this is the intended API workflow?

```
Cite.plugins.config.get('csl').templates.add('ieee', ieee_stylesheet);
let bibliography = new Cite();
bibliography.add(...);
bibliography.format('bibliography', {
    format: 'html',
    template: 'ieee'
});
```

**Comment by larsgw** [comment]
That *should* work. Only thing is that you can also pass items in the `Cite` constructor. As for the reason it doesn't work (I can't reproduce it so far), can you run this after adding `ieee`:

```
Object.keys(Cite.plugins.config.get('csl').templates.data)
```

**Comment by jczerwinski** [comment]
Or alternatively, bibliography.js grabbing a new engine, rather than the existing one?

**Comment by jczerwinski** [comment]
Nevermind, I think it's on me. Async things happening in unexpected order in my code. Thanks!
