### ISSUE TITLE
Can citation.js validate a bibtex file?

### ISSUE THREAD

**Issue by RichardEb** [larsgw/citation.js#162]
Can citation.js validate a bibtex file?

E.g. check if all required fields are available?

**Comment by larsgw** [comment]
Not yet, but that sounds like a good idea. Would this list ([source](http://www.openoffice.org/bibliographic/bibtex-defs.html)) suffice?:

<details>
<dl>
	<dt><strong>article</strong> 
	</dt><dd>
	An article from a journal or magazine. Required fields: <tt>author</tt>,
	<tt>title</tt>, <tt>journal</tt>, <tt>year</tt>. Optional fields:
	<tt>volume</tt>, <tt>number</tt>, <tt>pages</tt>, <tt>month</tt>,
	<tt>note</tt>. 
	</dd><dt>
	<strong>book</strong> 
	</dt><dd>
	A book with an explicit publisher. Required fields: <tt>author</tt>
	or <tt>editor</tt>, <tt>title</tt>, <tt>publisher</tt>, <tt>year</tt>.
	Optional fields: <tt>volume</tt> or <tt>number</tt>, <tt>series</tt>,
	<tt>address</tt>, <tt>edition</tt>, <tt>month</tt>, <tt>note</tt>. 
	</dd><dt>
	<strong>booklet</strong> 
	</dt><dd>
	A work that is printed and bound, but without a named publisher or
	sponsoring institution. Required field: <tt>title</tt>. Optional
	fields: <tt>author</tt>, <tt>howpublished</tt>, <tt>address</tt>,
	<tt>month</tt>, <tt>year</tt>, <tt>note</tt>. 
	</dd><dt>
	<strong>conference</strong> 
	</dt><dd>
	The same as <tt>INPROCEEDINGS</tt>, included for <i>Scribe</i>
	compatibility. 
	</dd><dt>
	<strong>inbook</strong> 
	</dt><dd>
	A part of a book, which may be a chapter (or section or whatever)
	and/or a range of pages. Required fields: <tt>author</tt> or <tt>editor</tt>,
	<tt>title</tt>, <tt>chapter</tt> and/or <tt>pages</tt>, <tt>publisher</tt>,
	<tt>year</tt>. Optional fields: <tt>volume</tt> or <tt>number</tt>,
	<tt>series</tt>, <tt>type</tt>, <tt>address</tt>, <tt>edition</tt>,
	<tt>month</tt>, <tt>note</tt>. 
	</dd><dt>
	<strong>incollection</strong> 
	</dt><dd>
	A part of a book having its own title. Required fields: <tt>author</tt>,
	<tt>title</tt>, <tt>booktitle</tt>, <tt>publisher</tt>, <tt>year</tt>.
	Optional fields: <tt>editor</tt>, <tt>volume</tt> or <tt>number</tt>,
	<tt>series</tt>, <tt>type</tt>, <tt>chapter</tt>, <tt>pages</tt>,
	<tt>address</tt>, <tt>edition</tt>, <tt>month</tt>, <tt>note</tt>. 
	</dd><dt>
	<strong>inproceedings</strong> 
	</dt><dd>
	An article in a conference proceedings. Required fields: <tt>author</tt>,
	<tt>title</tt>, <tt>booktitle</tt>, <tt>year</tt>. Optional fields:
	<tt>editor</tt>, <tt>volume</tt> or <tt>number</tt>, <tt>series</tt>,
	<tt>pages</tt>, <tt>address</tt>, <tt>month</tt>, <tt>organization</tt>,
	<tt>publisher</tt>, <tt>note</tt>. 
	</dd><dt>
	<strong>manual</strong> 
	</dt><dd>
	Technical documentation. Required field: <tt>title</tt>. Optional
	fields: <tt>author</tt>, <tt>organization</tt>, <tt>address</tt>,
	<tt>edition</tt>, <tt>month</tt>, <tt>year</tt>, <tt>note</tt>. 
	</dd><dt>
	<strong>mastersthesis</strong> 
	</dt><dd>
	A Master's thesis. Required fields: <tt>author</tt>, <tt>title</tt>,
	<tt>school</tt>, <tt>year</tt>. Optional fields: <tt>type</tt>,
	<tt>address</tt>, <tt>month</tt>, <tt>note</tt>. 
	</dd><dt>
	<strong>misc</strong> 
	</dt><dd>
	Use this type when nothing else fits. Required fields: none.
	Optional fields: <tt>author</tt>, <tt>title</tt>, <tt>howpublished</tt>,
	<tt>month</tt>, <tt>year</tt>, <tt>note</tt>. 
	</dd><dt>
	<strong>phdthesis</strong> 
	</dt><dd>
	A PhD thesis. Required fields: <tt>author</tt>, <tt>title</tt>,
	<tt>school</tt>, <tt>year</tt>. Optional fields: <tt>type</tt>,
	<tt>address</tt>, <tt>month</tt>, <tt>note</tt>. 
	</dd><dt>
	<strong>proceedings</strong> 
	</dt><dd>
	The proceedings of a conference. Required fields: <tt>title</tt>,
	<tt>year</tt>. Optional fields: <tt>editor</tt>, <tt>volume</tt> or
	<tt>number</tt>, <tt>series</tt>, <tt>address</tt>, <tt>month</tt>,
	<tt>organization</tt>, <tt>publisher</tt>, <tt>note</tt>. 
	</dd><dt>
	<strong>techreport</strong> 
	</dt><dd>
	A report published by a school or other institution, usually
	numbered within a series. Required fields: <tt>author</tt>, <tt>title</tt>,
	<tt>institution</tt>, <tt>year</tt>. Optional fields: <tt>type</tt>,
	<tt>number</tt>, <tt>address</tt>, <tt>month</tt>, <tt>note</tt>. 
	</dd><dt>
	<strong>unpublished</strong> 
	</dt><dd><p>
	A document having an author and title, but not formally published.
	Required fields: <tt>author</tt>, <tt>title</tt>, <tt>note</tt>.
	Optional fields: <tt>month</tt>, <tt>year</tt>.</p></dd></dl>
</details>

---

Easiest for me would be an API like this:

```js
Cite.plugins.config.get('input').strict = true
try {
  let data = Cite.input(bibtex)
  // valid
} catch (e) {
  // invalid
}
```
Do you have other ideas you'd like to share?

I'm currently a bit preoccupied with other things, so it might take a while until I have a patch, and more importantly a release. I'm probably able to work on things at the earliest in 2 weeks.

**Comment by RichardEb** [comment]
Everything sounds good to me. Thx

**Comment by retorquere** [comment]
For biblatex validation, a lot can be done from the `bcf` file; I have an automated checker generated from a bcf in https://gist.github.com/retorquere/c0aab4121960c8aef7df793cf28c31f9
