### ISSUE TITLE
Wikidata importer fails on special value types unknown and no-value

### ISSUE THREAD

**Issue by nichtich** [larsgw/citation.js#167]
If a property such as author (P50) is set to `no-value`, the Wikidata importer will fail with an error ("Cannot read property 'value' of undefined"). The special case "somevalue" must be treated specially because it the value may still be given as qualifier. See for an example <https://www.wikidata.org/wiki/Q57926700> where the editors (P98) are only known by name (qualifier named as (P1810))

**Comment by nichtich** [comment]
Interesting, I did not know about lerna before. This makes sense but adds another layer of complexity to the already intimidating `package.json`. About naming I'd stick to the established name `citation-js` for the umbrella package and add suffixes for individual packages, e.g. `citation-js-cli`, `citation-js-bibtex`... (but no `...-other`).

**Comment by larsgw** [comment]
> This makes sense but adds another layer of complexity to the already intimidating `package.json`.

Which `package.json`? Either way, this package will be exactly the same on the outside (same API, same way of importing, same URLs, same name, etc.) but just be a wrapper on the "inside".

> add suffixes for individual packages, e.g. `citation-js-cli`, `citation-js-bibtex`...

The individual packages will be available on npm under a [scope](https://docs.npmjs.com/misc/scope) as [`@citation-js/...`](https://www.npmjs.com/org/citation-js), with `plugin-` prefixed to distinguish plugins from other packages. My repo naming comment is about GitHub; I have the [citation-js](https://github.com/citation-js) organisation now, so `github.com/citation-js/citation-js` would be double, but `github.com/citation-js/citation.js` can be annoying with forks and `github.com/citation-js/core` is just untrue. I agree the first is the best option though.

> (but no `...-other`).

The `-other` package could be named "common" or "shared"; it's just basic functionality like JSON and URLs, and some shortcuts (HTML & jQuery elements). It will be included by default, as many other plugins depend on it, mainly the first parts.

**Comment by larsgw** [comment]
I see you opened an issue on this in wikidata-sdk too (https://github.com/maxlath/wikidata-sdk/issues/41). Can't do much with this at the moment.

https://runkit.com/larsgw/wdk-and-somevalue-novalue

**Comment by nichtich** [comment]
Yes, better wait until the simplification of special values is supported by wikidata-sdk.

**Comment by larsgw** [comment]
Well, I made a mistake in the commit message of https://github.com/citation-js/citation-js/commit/664644b39b078010b272ebd25c3f423d3be98868 but the next release should support `named as` so as soon as the simplification of special values while keeping qualifiers is fixed, it should work. I'll add a test case soon too.

**Comment by larsgw** [comment]
The item you provided works now, and I added some cases for other cases (novalue/somevalue but no qualifiers, novalue/somevalue on other properties) for which I haven't been able to find actual examples (which also means I haven't been able to test it properly).
