### ISSUE TITLE
Cite.input() ignores important bibtex fields

### ISSUE THREAD

**Issue by bdw1** [larsgw/citation.js#168]
Hello,

I tried to parse bibtex encoded data using the Cite.input() method. Unfortunately the parser ignores some fields that are defined in the bibtex standard(https://de.wikipedia.org/wiki/BibTeX). The following fields are ignored: school, organization, chapter, howpublished, institution
To make it worse the fields "school", "chapter" and "institution" are required fields in bibtex. So after parsing I don't even have a valid bibtex information.

Can you fix this please?

**Comment by RichardEb** [comment]
Any update here?

**Comment by larsgw** [comment]
Sorry, I'll be back after Wednesday next week, maybe earlier depending on if I can find the time. At that point, I'll work on a number of things, hopefully including this.

**Comment by larsgw** [comment]
Sorry this took so long, I'm working on improving the BibTeX mappings systematically. Progress can be tracked in https://github.com/citation-js/citation-js/issues/43 and https://github.com/citation-js/bibtex-mappings.

**Comment by larsgw** [comment]
This issue should be fixed in v0.5.0-alpha.10. If not, please re-open the issue.
