### ISSUE TITLE
Try/Catch Cite.Add() not throwing error forward

### ISSUE THREAD

**Issue by thelunararmy** [larsgw/citation.js#173]
Hi there,

Would it be possible to have the `Cite.add` function throw the error forward when encountering a Syntax error, rather than printing the error and then fail quietly?

Would be really nice to allow the the front end to report the entire faulty entry as opposed to just displaying the syntax error without content.

i.e.
```
let citer = new Cite();
for (let i = 0; i < listOfEntries; i++){
   try {
        await citer.addAsync(listOfEntries[i], {}, true);
    } catch (err) {
        // Handle using ui element
    }
} 
```
Currently this catch never triggers.

**Comment by EternalDeiwos** [comment]
Should be noted that the error in question comes from trying to parse bibtex records such as this:

```
@article{citekey,
  ...
  author={Garc{\'\i}a-Molina, H{\'e}ctor},
  ...
}
```

This was taken from Google Scholar and fails (like many others) with a syntax error because `{\'\i}` is "not a valid escape sequence".

**Comment by larsgw** [comment]
@thelunararmy I've been wanting to do something like that for a while now, including cutting down on other unnecessary log messages.

@EternalDeiwos That definitely seems like syntax that *should* be supported, and either way, I agree "not a valid escape sequence"  should be more like "unknown escape sequence".

**Comment by EternalDeiwos** [comment]
@larsgw Thanks. Looking forward to it.

**Comment by larsgw** [comment]
Some deadlines are getting in the way, about one more week I think.

**Comment by thelunararmy** [comment]
@larsgw No problem, thank you for the feedback! Much appreciated.
