### ISSUE TITLE
error when requesting more than 50 Wikidata qids

### ISSUE THREAD

**Issue by egonw** [larsgw/citation.js#176]
My [Groovy Cheminformatics](https://egonw.github.com/cdkbook/) books has more than 50 citations using Wikidata now, and I just got this error:

```
getEntities accepts 50 ids max to match Wikidata API limitations:
      this request won't get all the desired entities.
      You can use getManyEntities instead to generate several request urls
      to work around this limitation
```

The patch seems trivial: `s/getEntities/getManyEntities/` ?

**Comment by larsgw** [comment]
> The patch seems trivial: `s/getEntities/getManyEntities/` ?

Mostly yep, but also ([from `wikidata-sdk`](https://github.com/maxlath/wikidata-sdk/blob/master/docs/get_entities.md#get-many-entities-by-ids)):

> :warning: This limitation policy was probably there for a reason, right? This should be the exception, make sure to set an interval between your requests (500ms, 1s?)

---

[This code](https://github.com/citation-js/citation-js/blob/41eb3beb2a565f3cc1d07ba25a6d5b119c39926e/packages/plugin-wikidata/src/list.js#L17-L20):

```js
const parseWikidata = function (data) {
  const list = Array.isArray(data) ? data : data.trim().split(/(?:[\s,]\s*)/g)
  return [].concat(wdk.getEntities(list, ['en']))
}
```

Also [this](https://github.com/citation-js/citation-js/blob/c93136b71967a0fb738350444c3c1d7454fc7097/packages/plugin-wikidata/src/prop.js#L85) and the [async counterpart](https://github.com/citation-js/citation-js/blob/c93136b71967a0fb738350444c3c1d7454fc7097/packages/plugin-wikidata/src/prop.js#L188), although that should happen less often and should be modified anyway.

**Comment by larsgw** [comment]
Closed in https://github.com/citation-js/citation-js/pull/11
