### ISSUE TITLE
Problem with a translation

### ISSUE THREAD

**Issue by JohannaDangel** [larsgw/citation.js#178]
Hello,

we are designing a bilingual website. Our Czech partners informed us about a problem with a translation.
The field “volume” should be shown in the citation as “Svazek” which already is the translation for the field “volume” in the input mask.
But instead the abbreviation “Roč.” appears in the citation.
To sum up, the translation for said field differ in the input mask and in the output.

Is there a possibility to fix this?

**Input**
![Editing](https://user-images.githubusercontent.com/32933310/55159806-28859a00-5162-11e9-84e9-5648b9caa2d3.png)

**Output**
![Result](https://user-images.githubusercontent.com/32933310/55159848-4521d200-5162-11e9-8cf2-15327455c8ab.png)

**Comment by larsgw** [comment]
Formatted bibliography and citation output is generated with the [Citation Style Language (CSL)](https://citationstyles.org/), using [`citeproc-js`](https://citeproc-js.readthedocs.io). The localized abbreviations come from the [locale repository](https://github.com/citation-style-language/locales) (which you likely had to interact with, if you're using a Czech locale) and "volume" is mapped to "ročník" [there](https://github.com/citation-style-language/locales/blob/6b0cb4689127a69852f48608b6d1a879900f418b/locales-cs-CZ.xml#L164-L167), so we'd have to discuss it there. By the way, I'm seeing it being used the same [here](https://www.vsfs.cz/en/?id=2776-how-to-cite-sources), but I don't know that website.

**Comment by JohannaDangel** [comment]
Volume needs two different translations depending on the publication type. For articles (@article) and articles in conference proceedings (@inproceedings) the translation needs to be “ročník”.

For the rest it needs to be “svazek”.
The same differentiation is made for example in German as well (“Jahrgang” vs. “Band”).

**Comment by larsgw** [comment]
This issue is not specific to Citation.js. I did open an issue with CSL a while ago: https://github.com/citation-style-language/schema/issues/418
