### ISSUE TITLE
Ability to output only citation as such, e.g. [ABC99], [Tao03]

### ISSUE THREAD

**Issue by ComFreek** [larsgw/citation.js#182]
Is this library also able to output the pure citation, i.e. not the entry in the bibliography, but the citation in the text?
E.g. with alphabetical style, it could produce `[ABC99]` or `[Tao03]`.

I couldn't find related information in the docs or in the issue list. (Admittedly, I didn't quite know what to search for in the issue list. Searching for `citation` was not restrictice enough as you can imagine :smile:)

**Comment by larsgw** [comment]
True :slightly_smiling_face:

TL;DR: ([docs](https://citation.js.org/api/tutorial-cite_output.html))

```js
const cite = new Cite(data)

cite.format('citation', { template, ...options })
```

Story: Before `v0.4.0`, the output format for bibliographies was named `citation-STYLE` (where style is the template). With the transition from `Cite#get()` to `Cite#format()` there was the possibility to fix that, so now

```js
cite.get({ style: 'citation-apa' })
```

became

```js
cite.format('bibliography', { template: 'apa' })
```

which freed up the namespace to add

```js
cite.format('citation', { template: 'apa', entry: [id1, id2] })
```

Not entirely sure what template that would be though.

**Comment by ComFreek** [comment]
@larsgw Thanks for your answer! It seems like a simple plugin with a single output would do the job. I am not entirely sure whether I pursue to use citation.js. For my prototype application where I needed such functionality I hacked something together. Let's see if the prototype survives anyway :smile: (So anyone desiring this functionality, don't wait for me, go ahead yourself, I guess.)

PS: I was heavily confused not to find the sources in this repository (https://github.com/larsgw/citation.js) and then the apparent duplicate (?) repository https://github.com/citation-js/citation-js :smile:

**Comment by larsgw** [comment]
No problem, for just citation output it may be better to use [`citeproc-js`](https://github.com/Juris-M/citeproc-js) directly (or something else, if that works for you).

> PS: I was heavily confused not to find the sources in this repository (https://github.com/larsgw/citation.js) and then the apparent duplicate (?) repository https://github.com/citation-js/citation-js smile

Yeah, sorry, it's a mess. I intended to move from `larsgw/citation.js` to `citation-js/citation-js` but decided to keep this one for compatibility, which only made things more confusing. I'm thinking of coupling the two repositories more tightly, maybe with git submodules?
