### ISSUE TITLE
Support RIS as input format

### ISSUE THREAD

**Issue by TanguyHefnaoui** [larsgw/citation.js#184]
Feature request to support RIS as an input format as it already is available as output.

**Comment by larsgw** [comment]
I have no expected release date for this, but it's (now officially) on the TODO-list. See also https://github.com/citation-js/citation-js/issues/44

**Comment by larsgw** [comment]
I've been working on this, trying to make it following the specification (which I hadn't found earlier). However, today I found out there are *two* specs.

**Comment by larsgw** [comment]
Released in [`v0.4.9`](https://github.com/larsgw/citation.js/blob/master/CHANGELOG.md#049---2019-08-27).
