### ISSUE TITLE
Vue + citation-js error ReferenceError: regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by Rytiggy** [larsgw/citation.js#185]
I am running a Quasar app (framework built on top of Vue). 

this is my function im calling to generate a citation but I get the above error whenever I declare  `new Cite`
```javascript
 generateCitation() {
      const example = new Cite('Q21972834');

      const output = example.format('bibliography', {
        format: 'html',
        template: 'apa',
        lang: 'en-US',
      });

      console.log(output);
    },
```
As a note my require statement is at the top of the script.

Here is the actual error message:
![Screen Shot 2019-06-21 at 3 05 40 PM](https://user-images.githubusercontent.com/17414914/59945591-11d7a200-9436-11e9-9e17-378fec07acfd.png)

Any ideas what could be going on?

**Comment by larsgw** [comment]
Sorry for the slow response, this seems to have slipped through the cracks. It looks like the new `mjs` build (which gets used by Webpack) is expecting `@babel/polyfill`, which isn't there. The next release (`v0.4.8`) will have a patch in the build process which fixes the error when I try it.
