### ISSUE TITLE
Documentation for CSL Plugins incorrect?

### ISSUE THREAD

**Issue by jcarpenter** [larsgw/citation.js#192]
I think the [CSL Plugins docs](https://citation.js.org/api/tutorial-output_plugins_csl.html) may need to change `Cite.plugins.output.config.get('csl')` to `Cite.plugins.config.get('@csl')`?

Similar to #161, I was getting `undefined` errors whenever I tried to call `Cite.plugins.config.get`. I was following the instructions in the [CSL Plugins docs](https://citation.js.org/api/tutorial-output_plugins_csl.html). After some struggling, I found [Cite.plugins.list()](https://citation.js.org/api/Cite.plugins.html#.list) under the plugins docs, used it, found that `csl` is actually `@csl`. I then tried  to register my CSL template with `Cite.plugins.config.get('@csl')`, and found it worked.

Here's the full working code excerpt:

``` javascript
const references = fs.readFileSync('_input/citations/bib.json', 'utf8')

let cite = new Cite(references)

let stylesName = 'josh-csl'
let styles = fs.readFileSync('_input/citations/styles.csl', 'ascii')
Cite.plugins.config.get('@csl').templates.add(stylesName, styles)

var testCitation = cite.format('citation', {
    format: 'html',
    template: stylesName,
    lang: 'en-US',
    entry: ['wallace-wells2019']
})

console.log(testCitation)
```

citation-js@0.5.0-alpha.4, node v12.12.0, macOS 10.15

**Comment by larsgw** [comment]
> I think the CSL Plugins docs may need to change `Cite.plugins.output.config.get('csl')` to `Cite.plugins.config.get('@csl')`?

True, I think the docs are changed locally but I forgot to build them.

> After some struggling, I found `Cite.plugins.list()` under the plugins docs, used it, found that `csl` is actually `@csl`.

That's been bugging me too. I think I'll change it before `v0.5.0`.

**Comment by leafac** [comment]
I’ve been bitten by this as well.

By the way, this project is great! I’m very happy I’ve found it.

**Comment by leafac** [comment]
It seems that [`Cite.CSL.register.addTemplate()` works as well](https://github.com/larsgw/citation.js/blob/decbdd2c5b032920bc71d46dd40d35bc276c6fbc/index.js#L79-L98).

**Comment by ahtasham067** [comment]
![Capture](https://user-images.githubusercontent.com/48153435/141775084-779e3aa7-0be5-497f-8f00-922f51c2aac9.PNG)

**Comment by ahtasham067** [comment]
i am facing this problem while using CSL plugin?

**Comment by larsgw** [comment]
How are you importing citation.js?

**Comment by larsgw** [comment]
Let's carry this on in https://github.com/larsgw/citation.js/issues/219 if you're still interested.
