### ISSUE TITLE
use Wikidata webpage or resource IRI

### ISSUE THREAD

**Issue by egonw** [larsgw/citation.js#2]
Lars, currently the code points directly to the JSON:

    https://www.wikidata.org/wiki/Special:EntityData/Q23576506.json

That exposes implementation details. It would be better to use either the Wikidata webpage or the resource IRI, so respectively:

    https://www.wikidata.org/wiki/Q23576506
    http://www.wikidata.org/entity/Q23576506

If I make a patch for that somewhere this weekend, can you give it a test?

**Comment by larsgw** [comment]
I think I'll make it myself (if that's no problem), so I can make a filter to separate normal files from Wikidata webpages as well. Now, when a URL is passed, the code expects it to point directly to the data to use.

**Comment by larsgw** [comment]
Added support for passing Wikidata webpage or the resource IRI, but I haven't found a way yet to de-expose implementation details. Using Wikidata webpage or the resource IRI with a JSON accept header doesn't seem to work.

**Comment by larsgw** [comment]
Fixed by #13. Citation.js now uses the Wikidata api like this:

    'https://www.wikidata.org/w/api.php?' +
      'origin=*&' +
      'action=wbgetentities&' + 
      'ids=' + data.join( '|' ) + '&' +
      'languages=en&' +
      'format=json'

Where `data` is an array of Wikidata Entity Identifiers ("Q-numbers").

**Comment by larsgw** [comment]
Fixed by #13. Citation.js now uses the Wikidata api like this:

    'https://www.wikidata.org/w/api.php?' +
      'origin=*&' +
      'action=wbgetentities&' + 
      'ids=' + data.join( '|' ) + '&' +
      'languages=en&' +
      'format=json'

Where `data` is an array of Wikidata Entity Identifiers ("Q-numbers").
