### ISSUE TITLE
Add CODE_OF_CONDUCT.md to the project

### ISSUE THREAD

**Issue by sohamsshah** [larsgw/citation.js#209]
CODE_OF_CONDUCT file can be quite useful for any contributor/user to read and understand the community culture at citation-js.

It can include:
- Pledge
- Standards
- Responsibilites
- Enforcement etc.

Refer [this](https://www.contributor-covenant.org/version/1/4/code-of-conduct.html)

Let me know if I can work on this issue.

**Comment by larsgw** [comment]
Thank you very much for raising this issue. However, I will have to come back to this a bit later as I do not have much time for the next two weeks.

**Comment by larsgw** [comment]
I added a code of conduct to the @citation-js organization (to which I am planning to transfer this repository). Thank you!

**Comment by sohamsshah** [comment]
Is there any other issue/feature I can work on?

**Comment by larsgw** [comment]
I can think of some things:

  - Helping increase test coverage:
    - Create varied BibTeX or RIS files and their corresponding CSL-JSON representation
    - Add unit tests for [`@citation-js/core`](https://github.com/citation-js/citation-js/tree/v0.5/packages/core) ([current coverage](https://codecov.io/gh/citation-js/citation-js/tree/v0.5/packages/core/src/util))
  - Work on a specific issue (is https://github.com/citation-js/citation-js/issues/104 interesting for you?)
