### ISSUE TITLE
Add support for `dataset` of BibLaTeX

### ISSUE THREAD

**Issue by bellerophons-pegasus** [larsgw/citation.js#212]
BibLaTeX now also provides support to accomodate information about a dataset for citation with the type `@dataset`. It would be very helpful if citation.js could also support this. Currently when this is found it is automatically mapped to `@book`.

**Comment by larsgw** [comment]
What version are you using? I believe the most recent version (`v0.5.0-alpha.10`) should support it already.

**Comment by bellerophons-pegasus** [comment]
We were using the latest stable release. But now with `v0.5.0-alpha.10` `@dataset` is supported. Thank you for the tip. 

BTW: the [data model for `@dataset` in BibLaTeX](https://github.com/plk/biblatex/issues/1103) might be expanded; anybody is welcome to join the discussion.

**Comment by larsgw** [comment]
`v0.5.0-alpha.10` is pretty much ready to move to stable, I was just waiting to see if there were any bug reports.

 > BTW: the data model for @dataset in BibLaTeX might be expanded; anybody is welcome to join the discussion.

Thanks for the tip, I'll take a look later.
