### ISSUE TITLE
Import reference by DOI

### ISSUE THREAD

**Issue by larsgw** [larsgw/citation.js#25]
This is the easiest by just looking it up in Wikidata, but papers there are limited.

**Edit:** I take this back, by the way. It's just that I hadn't heard of Crossref, Citoid or DOI content negotiation yet, and that I was really impressed by the Wikidata API.

**Comment by zuphilip** [comment]
You can also try the Citoid endpoint, e.g. https://citoid.wikimedia.org/api?format=mediawiki&search=https%3A%2F%2Fdoi.org%2F10.1561%2F1900000056

**Comment by larsgw** [comment]
Well I didn't know about the CrossRef API when I posted this. I think I'll use that, as the response seems to be CSL-JSON (the format Citation.js uses internally), so it won't have to be parsed.

**Comment by zuphilip** [comment]
Actually, you can also use content negotiation which will be redirected through doi.org and CSL-JSON is supported by CrossRef, DataCite and mEDRA, e.g.
```
curl -LH "Accept: application/vnd.citationstyles.csl+json" https://doi.org/10.1126/science.169.3946.635
```
See http://citation.crosscite.org/docs.html

**Comment by larsgw** [comment]
## Update

* async (with the fetch api) works in both node.js and browser
* sync works in node.js (after a lot of debugging, turns out the relevant dependency drops headers after redirects and the option to turn that off is only documented in sub-dependencies)
* sync in browser doesn't work yet, but hey, the error handling does!

**Comment by larsgw** [comment]
Corresponding issues in the Crossref API repo: https://github.com/CrossRef/rest-api-doc/issues/221, https://github.com/CrossRef/rest-api-doc/issues/222

**Comment by larsgw** [comment]
## Update 3

* The HTTP -> HTTPS issue seems to be fixed, I'm waiting for confirmation.
* I am writing, implementing and testing some code to
    1. transform known Crossref DOI deviations (from CSL) to proper CSL
    2. transform known standard deviations (from CSL) to proper CSL
    3. drop unsupported props
* Consequentially, most stuff should work in a short while
