### ISSUE TITLE
BibTeX processing does not handle booktitle in inproceedings

### ISSUE THREAD

**Issue by mdekstrand** [larsgw/citation.js#26]
BibTeX processing does not support `booktitle` being specified directly in an `@inproceedings` entry, which is commonplace in the BibTeX export from many tools (such as Zotero). The test case seems to only use a `crossref` to `@proceedings`.

Example that reproduces this issue: [citation.txt](https://github.com/larsgw/citation.js/files/725279/citation.txt)

**Comment by larsgw** [comment]
Mapping fields from different formats is always a work in progress! I'll add it as fast as possible. I currently don't have anything set up for fields only being parsed in certain publication types, that's maybe something for [`v0.3.0`](https://github.com/larsgw/citation.js/projects/2).

**Comment by larsgw** [comment]
I hope this is what you meant. I mapped `booktitle` to `container-title` (as per Zotero mappings) and `series` to `collection-title`.
