### ISSUE TITLE
Make custom template and locale functioning easier

### ISSUE THREAD

**Issue by larsgw** [larsgw/citation.js#40]
The current way of using custom templates and locales is confusing to say the best (see #28). Expected features:

- default and custom template and locale registers, with appropriate methods
- way to amend templates

**Comment by larsgw** [comment]
I outlined some possible APIs in a [recent blogpost](https://larsgw.blogspot.nl/2017/07/citationjs-doi-update-and-more-stability.html#better-custom-formatted-citations):

```js
const template = '...'
const templateName = 'custom'

// Suggested new API
Cite.CSL.template.register(templateName, template)

// Nothing new, will stay the same
const data = new Cite(...)
data.get({
  type: 'html',
  style: 'citation-' + templateName
})
```

```js
// prepends the id like this: "[$ID]: "
const prepend = ({id}) => `[${id}]: `
// appends an altmetric widget
const append = ({DOI}) => `<span class='altmetric-embed' data-doi='${DOI}'></span>`

// Nothing new, will stay the same
const data = new Cite(...)
data.get({
  type: 'html',
  style: 'citation-' + templateName,
  // Suggested new API
  // both properties either function or constant string
  append: append,
  prepend: prepend
})
```
---
I'm currently working on the implementation, and it will be slightly different, but not structurally (probably only method names):

```js
const template = '...'
const templateName = 'custom'

// Suggested new API
Cite.CSL.register.addTemplate(templateName, template)

// Nothing new, will stay the same
const data = new Cite(...)
data.get({
  type: 'html',
  style: 'citation-' + templateName
})
```

**Comment by larsgw** [comment]
I failed to mention this here earlier, but the first part of the API change happened in 3aaaf7ce4b1e77cf7c85e6e8be1a064435f9b5d1 (or `v0.3.0-11`). For current API, see [here for templates](https://github.com/larsgw/citation.js#cite.out.templates) and [here for locales](https://github.com/larsgw/citation.js#cite.out.locales). Ping @austinjp.

**Comment by austinjp** [comment]
Great work @larsgw , really appreciate it. I'll have a detailed look another day!
