### ISSUE TITLE
Add Bib.TXT support

### ISSUE THREAD

**Issue by larsgw** [larsgw/citation.js#47]
Add [Bib.TXT](http://bibtxt.github.io/) support. I would leave this to [`v0.4`](https://github.com/larsgw/citation.js/projects/3), which focuses on more and better input formats, but it seems like such a simple thing to do, and I don't want to wait for me to finish `v0.3`.

**Comment by larsgw** [comment]
# Specifications

Some collected specifications. Please do tell if I got something wrong.

From [the site](http://bibtxt.github.io/):

  * values are in unicode
  * values don't have to be in quotes
  * commas between key-value pairs can be omitted as well
  * all keys and values can be mapped directly to bibtex, except for the unicode chars
  * general format:

```
[<KEY>]
  author:    <AUTHOR>
  title:     <TITLE>
  <ETC>:     <OTHER BIBTEX FIELDS>
```

See also the topic I made for more info on specifications: https://groups.google.com/d/msg/wwwmake/1YXxKhpdrCE/OpfFzsmOAAAJ

Main points as of writing:

  * whitespace doesn't really matter, except newlines
  * values can't have leading or trailing spaces, as they're auto-trimmed (might get more info on this)

**Comment by geraldb** [comment]
Hello,
   great to see support in citation.js   About leading and trailings spaces in values - if they are really significant than the proposal is to use quotes e.g. "    Title   "  - not sure if there's a real use case. Would appreciate a "real world" example. Keep up the great work. Greatly appreciated. Cheers.

**Comment by larsgw** [comment]
Demo at [demo/bibtxt.html](https://larsgw.github.io/citation.js/demo/bibtxt.html).

**Comment by geraldb** [comment]
Hello,
   Wow. Again thanks for the great work on adding Bib.txt. Will try to update the website shortly to add citations.js etc.  Have a great weekend. Cheers.
