### ISSUE TITLE
DOI sync fetching doesn't work in Chrome

### ISSUE THREAD

**Issue by larsgw** [larsgw/citation.js#51]
**Note:** Relevant commit not pushed to repo or npm yet as of writing this.

Error message:

    GET https://doi.org/$DOI

**Comment by egonw** [comment]
Once fixed, you can add an answer to this SE question: https://writers.stackexchange.com/questions/5318/how-to-convert-doi-to-citation-information

**Comment by larsgw** [comment]
Note (to self): this is a browser issue

**Comment by larsgw** [comment]
### More info

This tweet chain:

<blockquote class="twitter-tweet" data-lang="nl"><p lang="en" dir="ltr">Using XmlHttpRequest, sync request gives status=0, no further (error) message or anything. Both async and the Fetch API DO work. Why?</p>&mdash; Lars Willighagen (@larswillighagen) <a href="https://twitter.com/larswillighagen/status/887689060432695298">19 juli 2017</a></blockquote>

This StackOverflow question (mine):

> "Consider three domains: A, B and C. A piece of JavaScript code on domain A makes a standard **synchronous** `XMLHttpRequest` `GET` call to domain B, with only a `Accept` header, apart from the default ones. Domain B then redirects to domain C. Both responses (B and C) have the `Access-Control-Allow-Origin` set to `*`. This works fine in Firefox and, as I have heard, in Internet Explorer too. However, Chrome doesn't seem to allow this. Asynchronous code, however, does work, also in Chrome.<br>
Both synchronous and asynchronous requests directly to domain C (and the hypothetical domain D with the same properties) *do* work.<br>
..."<br>
https://stackoverflow.com/q/45238537/5095300

**Comment by larsgw** [comment]
Seems fixed since Chrome 69, actually (never noticed though).
