### ISSUE TITLE
Double-delimited fields such as author should not decompose

### ISSUE THREAD

**Issue by austinjp** [larsgw/citation.js#54]
Double-delimiters in bibtex are used to denote fields that should not decompose. Such fields should be converted to literals. (See [this on tex.se](https://tex.stackexchange.com/a/109070))

So for example:

```bibtex
@article{id1,
  author: "{Smiling Sam}"
}
@article{id2,
  author: {{Good Guy Greg}}
}
```

...should convert to something approximating this pseudo-JSON:

```
[ { author: [ { literal: 'Smiling Sam' } ],
       type: 'article-journal',
       label: 'id1',
       id: 'id1' },
     { author: [ { literal: 'Good Guy Greg' } ],
       type: 'article-journal',
       label: 'id2',
       id: 'id2' } ]
```

Instead the actual JSON shows that the double-delimited author fields have been decomposed to "family" and "given" names, see https://runkit.com/austinjp/597b3327f8b6e60012bc5ac5

Citation-js currently appears to support literals only for author. Perhaps literals are necessary for other fields such as title, journal, etc. However author is certainly the most pressing. Consider an author defined as ```{{National Academy of Sciences}}```. This currently decomposes to something like ```of N. A.```. Author names of this type are very common.

**Comment by larsgw** [comment]
Yep. Pretty big issue. Thanks for reporting!

Some related symptoms:
1. Names (of institutions) can't have ` and ` in it now (`author = {{Uni. for A and B} and Lars Willighagen}`)
2. Everything breaks when brackets aren't matched from beginning to end (see example above, or `author = {{a} and b}`)

---

Some ideas for other things:

* `date` can be parsed into `{literal: "..."}` instead ([valid CSL](https://github.com/citation-style-language/schema/blob/master/csl-data.json#L235-L237) when using `date={{...}}`
* That's about it, as there aren't any other parsed values (except pages), and case is handled by the template and citeproc anyway.

**Comment by larsgw** [comment]
Literals now work as intended. However, literal `"`s in dubbel-quote-delimited values and `{}`s don't. I'm reopening now, but I can't work on it until next week or so.

(I'm on mobile, so sorry for the short sentences)

**Comment by austinjp** [comment]
Thanks for all your work on this @larsgw , much appreciated.

**Comment by larsgw** [comment]
Literal `"`s are now supported as `\`-escaped characters (not the best, I know), literal `{}`s not yet, but that's normally difficult in BibTeX.
