### ISSUE TITLE
Support @STRING, @̶P̶R̶E̶A̶M̶B̶L̶E̶ and @COMMENT and string concatenation (`#`) in BibTeX

### ISSUE THREAD

**Issue by larsgw** [larsgw/citation.js#56]
Most info can be found [here](http://www.bibtex.org/Format/).

**Comment by larsgw** [comment]
Welp, `@PREAMBLE` proves LaTeX-specific, guess I should have looked into that before blindly posting a feature-request.

**Comment by nichtich** [comment]
The best description so far I found at <https://github.com/aclements/biblib#recognized-grammar>

**Comment by larsgw** [comment]
Do you have a problem with the new implementation (apart from https://github.com/citation-js/citation-js/issues/73) or is this just additional information?

**Comment by larsgw** [comment]
This issue should be fixed in v0.5.0-alpha.10. If not, please re-open the issue.
