### ISSUE TITLE
Change and add Wikidata publication type mappings

### ISSUE THREAD

**Issue by larsgw** [larsgw/citation.js#78]
See also #76 

---

| Wikidata item | Current mapping | Expected mapping | Notes | Status |
|---|---|---|---|---|
|[`Q49848`](https://wikidata.org/wiki/Q49848)|`-`|`article`|via Zotero/zotkat|v0.3.3|
|[`Q38926`](https://wikidata.org/wiki/Q38926)|`-`|`article-newspaper`|right?|v0.3.3|
|[`Q5707594`](https://wikidata.org/wiki/Q5707594)|`-`|`article-newspaper`||v0.3.3|
|[`Q30070590`](https://wikidata.org/wiki/Q30070590)|`-`|`article-magazine`||v0.3.3|
|[`Q686822`](https://wikidata.org/wiki/Q686822)|`-`|`bill`||v0.3.3|
|[`Q1555508`](https://wikidata.org/wiki/Q1555508)|`-`|`broadcast`|via Zotero|v0.3.3|
|[`Q15416`](https://wikidata.org/wiki/Q15416)|`-`|`broadcast`|via Zotero|v0.3.3|
|[`Q1980247`](https://wikidata.org/wiki/Q1980247)|`-`|`chapter`||v0.3.3|
|[`Q1172284`](https://wikidata.org/wiki/Q1172284)|`-`|`dataset`||v0.3.3|
|[`Q10389811`](https://wikidata.org/wiki/Q10389811)|`-`|`entry`|via Zotero|v0.3.3|
|[`Q19389637`](https://wikidata.org/wiki/Q19389637)|`-`|`entry`|used for both dictionaries and encyclopedias|v0.3.3|
|[`Q17329259`](https://wikidata.org/wiki/Q17329259)|`-`|`entry-encyclopedia`|via Zotero|v0.3.3|
|[`Q30070753`](https://wikidata.org/wiki/Q30070753)|`-`|`figure`||v0.3.3|
|[`Q1027879`](https://wikidata.org/wiki/Q1027879)|`-`|`graphic`||v0.3.3|
|[`Q4502142`](https://wikidata.org/wiki/Q4502142)|`-`|`graphic`||v0.3.3|
|[`Q478798`](https://wikidata.org/wiki/Q478798)|`-`|`graphic`||v0.3.3|
|[`Q838948`](https://wikidata.org/wiki/Q838948)|`-`|`graphic`|via Zotero|v0.3.3|
|[`Q178651`](https://wikidata.org/wiki/Q178651)|`-`|`interview`||v0.3.3|
|[`Q49371`](https://wikidata.org/wiki/Q49371)|`-`|`legislation`||v0.3.3|
|[`Q820655`](https://wikidata.org/wiki/Q820655)|`-`|`legislation`||v0.3.3|
|[`Q2334719`](https://wikidata.org/wiki/Q2334719)|`-`|`legal_case`||v0.3.3|
|[`Q87167`](https://wikidata.org/wiki/Q87167)|`-`|`manuscript`||v0.3.3|
|[`Q4006`](https://wikidata.org/wiki/Q4006)|`-`|`map`||v0.3.3|
|[`Q11424`](https://wikidata.org/wiki/Q11424)|`-`|`motion_picture`||v0.3.3|
|[`Q30070675`](https://wikidata.org/wiki/Q30070675)|`-`|`motion_picture`|via Zotero|v0.3.3|
|[`Q187947`](https://wikidata.org/wiki/Q187947)|`-`|`musical_score`||v0.3.3|
|[`Q18536349`](https://wikidata.org/wiki/Q18536349)|`-`|`pamphlet`||v0.3.3|
|[`Q190399`](https://wikidata.org/wiki/Q190399)|`-`|`pamphlet`||v0.3.3|
|[`Q26973022`](https://wikidata.org/wiki/Q26973022)|`-`|`paper-conference`||v0.3.3|
|[`Q23927052`](https://wikidata.org/wiki/Q23927052)|`-`|`paper-conference`||v0.3.3|
|[`Q253623`](https://wikidata.org/wiki/Q253623)|`-`|`patent`||v0.3.3|
|[`Q30070565`](https://wikidata.org/wiki/Q30070565)|`-`|`personal_communication`|via Zotero|v0.3.3|
|[`Q30070439`](https://wikidata.org/wiki/Q30070439)|`-`|`personal_communication`|via Zotero/zotkat|v0.3.3|
|[`Q133492`](https://wikidata.org/wiki/Q133492)|`-`|`personal_communication`|via Zotero/zotkat|v0.3.3|
|[`Q628523`](https://wikidata.org/wiki/Q628523)|`-`|`personal_communication`||v0.3.3|
|[`Q7216866`](https://wikidata.org/wiki/Q7216866)|`-`|`post`|via Zotero/zotkat|v0.3.3|
|[`Q17928402`](https://wikidata.org/wiki/Q17928402)|`-`|`post-blog`||v0.3.3|
|[`Q10870555`](https://wikidata.org/wiki/Q10870555)|`-`|`report`||v0.3.3|
|[`Q265158`](https://wikidata.org/wiki/Q265158)|`-`|`review`||v0.3.3|
|[`Q637866`](https://wikidata.org/wiki/Q637866)|`-`|`review-book`||v0.3.3|
|[`Q7366`](https://wikidata.org/wiki/Q7366)|`-`|`song`||v0.3.3|
|[`Q3741908`](https://wikidata.org/wiki/Q3741908)|`-`|`song`|via Zotero|v0.3.3|
|[`Q30070318`](https://wikidata.org/wiki/Q30070318)|`-`|`song`|via Zotero/zotkat|v0.3.3|
|[`Q24634210`](https://wikidata.org/wiki/Q24634210)|`-`|`song`|via Zotero|v0.3.3|
|[`Q861911`](https://wikidata.org/wiki/Q861911)|`-`|`speech`||v0.3.3|
|[`Q1266946`](https://wikidata.org/wiki/Q1266946)|`-`|`thesis`||v0.3.3|
|[`Q187685`](https://wikidata.org/wiki/Q187685)|`-`|`thesis`||v0.3.3|
|[`Q131569`](https://wikidata.org/wiki/Q131569)|`-`|`treaty`||v0.3.3|
|[`Q36774`](https://wikidata.org/wiki/Q36774)|`-`|`webpage`||v0.3.3|

> * 'unreleased' is implemented, but not yet released
> * versions in the status column mean completed in $VERSION

---

**WIP. Feel free to add more mappings.**

Helpful docs:

* https://github.com/zotero/translators/blob/master/Wikidata.js with https://aurimasv.github.io/z2csl/typeMap.xml
* Pre-existing mappings: https://github.com/larsgw/citation.js/blob/416a844c0a33b825e2ff781287ab7febec2cdce6/src/parse/wikidata/type.js#L8-L14

**Comment by zuphilip** [comment]
I use this map for mapping Zotero itemTypes to Wikidata: https://github.com/UB-Mannheim/zotkat/blob/bfc1f795f3500a99b9345368b91b2f2be68bfe9b/Wikidata%20QuickStatements.js#L40-L86

**Comment by zuphilip** [comment]
> I'd call a podcast a speech, but Zotero doesn't. Via Zotero

Zotero has an item type podcast, but this is mapped to the CSL type song, see https://aurimasv.github.io/z2csl/typeMap.xml

**Comment by larsgw** [comment]
I know Zotero has a podcast type, and that it maps to CSL song type; that's what I meant. I think I remember seeing a discussion (or comment) somewhere on whether that's appropriate or not, but I can't remember where.

I'll take a look at the zotkat mappings (and I think I forgot stuff from the translator too).

**Comment by larsgw** [comment]
All in this batch are implemented, I'll close this for now.
