### ISSUE TITLE
Possibility to create/offer modular builds

### ISSUE THREAD

**Issue by meinbrodt** [larsgw/citation.js#88]
Hi,

I think it would be a great idea to be able to create/download modular builds. At first glance a good approach could be to have a core module + pluggable modules that would support the different output and input data formats.

My rationale: I'm currently integrating this library in a browser-based project of mine where I only have to deal with bibtex as input data, however I still have to use the whole library with all the other unused functionality which increases the file size of the library unnecessarily.

Best regards, Matthias

**Comment by larsgw** [comment]
Hi, I was thinking of doing this as well. It's my main goal for [Version 0.4](https://github.com/larsgw/citation.js/projects/3), although I haven't expressed that anywhere yet.

I'm currently working on making an API to register additional parsers and am moving all 'native' parsers to use that API as well. Progress on output plugins can be tracked in #82.

**Comment by meinbrodt** [comment]
Awesome! :-)

**Comment by larsgw** [comment]
The most difficult part seems to abstract the type parsing system, as the old one had some very non-abstract things to hold everything together. After that, the only hurdle left should be creating some kind of convenient system to bundle the parsing modules on demand.

Things that _do_ work already:

- The data parsing (after the input type is determined) is all done via the new parser-plug-in method
- I have organised most data parsers into 4 modules, in a separate `modules/` directory (in the `src/parse/` dir), where they are imported and registered by a index file
- Each module can export some metadata (currently only the scope, which is part of a new type name 'syntax')
- This syntax consists of `@SCOPE/FORMAT+TYPE`, where `SCOPE` is the overall format name (e.g. `wikidata`, `bibtex`), `FORMAT` is the way the citation info is conveyed (e.g. `list`, `url`), and `TYPE` the data type with which this is done (e.g. `text` or `object`) _(This isn't really important for people that don't use the type names)_
- All data parsers can still be found as static properties too, with `Cite.parse.*()` (function name is determined by input type name)

> I may have mixed up combinations of 'format', 'parse', 'input' and 'type' here a lot, but you should see the variable naming: a complete mess. I hope it doesn't distract from what I'm trying to say too much, and I'll try to improve the code soon

**Comment by larsgw** [comment]
**Note: all this is only yet in the [dev/parsing-infrastructure](https://github.com/larsgw/citation.js/tree/dev/parsing-infrastructure) branch**

Finally, the parsing system [allows for modules](https://github.com/larsgw/citation.js/blob/dev/parsing-infrastructure/README.md#plugins.in). Also, all native parsers are divided according to these modules. I still need to set up a way to actually easily create modular the build files, but it's something. The code is not that messy either anymore, although the API still is (IMO). These things will probably be improved in v0.4, as other things, like output, will get modularized then too.

Sorry for the delay since the last update, the type parsing mechanism proved quite difficult (and still has some issues).

**Comment by larsgw** [comment]
Hi @meinbrodt, I just wanted to given you a quick update on this. In the most recent versions (i.e. `v0.4.0-4`), the different input and output formats already behave quite like modules. Apart from some small API and namespace changes, this will probably be ready somewhat soon. However, I was wondering if you had any opinions on how to actually offer these builds in a modular way.

I just published a Citation.js plugin as a separate package ([here](https://www.npmjs.com/package/@citation-js/plugin-software-formats)), partly as a trial for this. The API to use this plugin is simple:

```js
require('@citation-js/plugin-software-formats')
```

This automatically registers the different formats to the `Cite` object, and even allows for some configuration. Do you think this would be a good way to do this? Of course, if you want a lot of different plugins, getting them like this can be quite tedious. I could however offer presets, just [like Babel does](https://babeljs.io/docs/plugins/#presets). Do you think that would work?

**Comment by larsgw** [comment]
@meinbrodt, I'm glad to announce this is fully implemented in `0.4.0-11`. I can't believe it took more than a year to finish everything.

* The different modules can be found at https://github.com/citation-js/citation-js and on npm at https://npmjs.com/org/citation-js.
* There are some slight differences between exports of `@citation-js/core` and `citation-js` which I'll document properly later
* You can check out a build tool here: https://github.com/citation-js/bundle-tool. You'd have to update version numbers in `package.json`, then use the UI or call the API `/bundle` with query params:
    * `c` - include core?
    * `p` - include specific plugin (use param multiple times for multiple params)

If encounter any problems, please do report back!
