### ISSUE TITLE
Biblatex Support

### ISSUE THREAD

**Issue by kloppen** [larsgw/citation.js#94]
I think that support for biblatex, in addition to bibtex, would be very useful, mainly because biblatex support many more fields (abstract, file, etc.).

I would think that support for biblatex could be added by using most of the existing bibtex code, but adding a new set of fields (and mappings between the biblatex fields and CSL).

For reference, the manual for biblatex can be found at the link below. It includes a listing of all the fields.
http://mirrors.ibiblio.org/CTAN/macros/latex/contrib/biblatex/doc/biblatex.pdf

**Comment by larsgw** [comment]
Would it be possible to add those fields to the BibTeX parser to create a parser that does both, or are they not that compatible?

---

Side thought: Probably the best way is is by setting up JSON-LD support and parsing BibTeX/BibLaTeX text into that instead. If the internal data format is JSON-LD, with translators between schemes, things could be a lot easier, more durable and better, as information wouldn't be lost in processing, because formats would only be converted when needed. However, that's a lot of work, with a lot of pitfalls, such as converting data types, collecting scheme URIs, and merging schemes, and is perhaps better fit for v0.5 (as v0.4 will be the modular i/o system).

**Comment by kloppen** [comment]
It seems that BibLaTex is a super-set of BibTex, so it should be possible to add the extra fields to the existing BibTeX class. However, I think that there should be an option to allow users to get pure BibTeX from the get method. There are a number of Entry Types that exist only in BibLaTeX: these extra Entry Types would cause problems in a .bib file that someone is using for BibTeX.

I've put together a table of concordance between the BibTeX and BibLaTeX fields and Entry Types below. All information is from the two following references:

http://ctan.forsale.plus/biblio/bibtex/base/btxdoc.pdf
http://mirrors.ibiblio.org/CTAN/macros/latex/contrib/biblatex/doc/biblatex.pdf

| *BibTeX Field*    | *BibLaTeX Field*                           |     *BibLaTeX Type*       |
|--------------|--------------------------------------|--------------------|
|              | abstract                             | literal            |
|              | addendum                             | literal            |
| address      | address (alias for location)         | list (literal)     |
|              | afterword                            | list (name)        |
|              | annotation                           | literal            |
|              | annotator                            | list (name)        |
| annote       | annote (alias for annotation)        | literal            |
|              | archiveprefix (alias for eprinttype) | literal            |
| author       | author                               | list (name)        |
|              | authortype                           | key                |
|              | bookauthor                           | list (name)        |
|              | bookpagination                       | key                |
|              | booksubtitle                         | literal            |
| booktitle    | booktitle                            | literal            |
|              | booktitleaddon                       | literal            |
| chapter      | chapter                              | literal            |
|              | commentator                          | list (name)        |
| crossref     | crossref                             | entrykey           |
|              | date                                 | date               |
|              | doi                                  | verbatim           |
| edition      | edition                              | integer or literal |
| editor       | editor                               | list (name)        |
|              | editora                              | list (name)        |
|              | editorb                              | list (name)        |
|              | editorc                              | list (name)        |
|              | editortype                           | key                |
|              | editoratype                          | key                |
|              | editorbtype                          | key                |
|              | editorctype                          | key                |
|              | eid                                  | literal            |
|              | entrysubtype                         | literal            |
|              | eprint                               | verbatim           |
|              | eprintclass                          | literal            |
|              | eprinttype                           | literal            |
|              | eventdate                            | date               |
|              | eventtitle                           | literal            |
|              | eventtitleaddon                      | literal            |
|              | file                                 | verbatim           |
|              | foreword                             | list (name)        |
|              | holder                               | list (name)        |
| howpublished | howpublished                         | literal            |
|              | indextitle                           | literal            |
| institution  | institution                          | list (literal)     |
|              | introduction                         | list (name)        |
|              | isan                                 | literal            |
|              | isbn                                 | literal            |
|              | ismn                                 | literal            |
|              | isrn                                 | literal            |
|              | issn                                 | literal            |
|              | issue                                | literal            |
|              | issuesubtitle                        | literal            |
|              | issuetitle                           | literal            |
|              | iswc                                 | literal            |
| journal      | journal (alias for journaltitle)     | literal            |
|              | journalsubtitle                      | literal            |
|              | journaltitle                         | literal            |
| key          | key (alias for sortkey)              | literal            |
|              | label                                | literal            |
|              | language                             | list (key)         |
|              | library                              | literal            |
|              | location                             | list (literal)     |
|              | mainsubtitle                         | literal            |
|              | maintitle                            | literal            |
|              | maintitleaddon                       | literal            |
| month        | month                                | datepart           |
|              | nameaddon                            | literal            |
| note         | note                                 | literal            |
| number       | number                               | integer            |
| organization | organization                         | list (literal)     |
|              | origdate                             | date               |
|              | origlanguage                         | key                |
|              | origlocation                         | list (literal)     |
|              | origpublisher                        | list (literal)     |
|              | origtitle                            | literal            |
| pages        | pages                                | range              |
|              | pagetotal                            | literal            |
|              | pagination                           | key                |
|              | part                                 | literal            |
|              | pdf (alias for file)                 | verbatim           |
|              | primaryclass (alias for eprintclass) | literal            |
| publisher    | publisher                            | literal            |
|              | pubstate                             | key                |
|              | reprinttitle                         | literal            |
| school       | school (alias for institution)       | list (literal)     |
| series       | series                               | literal            |
|              | shortauthor                          | list (name)        |
|              | shorteditor                          | list (name)        |
|              | shorthand                            | literal            |
|              | shorthandintro                       | literal            |
|              | shortjournal                         | literal            |
|              | shortseries                          | literal            |
|              | shorttitle                           | literal            |
|              | subtitle                             | literal            |
| title        | title                                | literal            |
|              | titleaddon                           | literal            |
|              | translator                           | list (name)        |
| type         | type                                 | key                |
|              | url                                  | uri                |
|              | urldate                              | date               |
|              | venue                                | literal            |
|              | version                              | literal            |
| volume       | volume                               | integer            |
|              | volumes                              | integer            |
| year         | year                                 | literal            |


| *BibTeX Entry Type* | *BibLaTeX Entry Type*                   |
|-------------------|---------------------------------------|
| article           | article                               |
| book              | book                                  |
|                   | bookinbook                            |
| booklet           | booklet                               |
|                   | collection                            |
| conference        | conference (alias for inproceedings) |
|                   | electronic (alias for online)        |
| inbook            | inbook                                |
| incollection      | incollection                          |
| inproceedings     | inproceedings                         |
|                   | inreference                           |
| manual            | manual                                |
| mastersthesis     | mastersthesis (alias for thesis)     |
| misc              | misc                                  |
|                   | mvbook                                |
|                   | mvcollection                          |
|                   | mvproceedings                         |
|                   | mvreference                           |
|                   | online                                |
|                   | patent                                |
|                   | periodical                            |
| phdthesis         | phdthesis (alias for thesis)         |
| proceedings       | proceedings                           |
|                   | reference                             |
|                   | set                                   |
|                   | suppbook                              |
|                   | suppcollection                        |
|                   | suppperiodical                        |
|                   | thesis                                |
| techreport        | techreport (alias for report)        |
| unpublished       | unpublished                           |
|                   | www (alias for online)               |
|                   | xdata                                 |
|                   |                                       |


BibLaTeX also has a number of "Unsupported" Entry Types. I believe that most of these have direct analogous to types in CSL, so I think it would be worthwhile to include them (maybe as an option?)

| *Unsupported Types*                     |
|--------------------------------------------|
 | artwork                               |
| audio                                 |
| bibnote                               |
| commentary                            |
| image                                 |
| jurisdiction                          |
| legislation                           |
| legal                                 |
| letter                                |
| movie                                 |
| music                                 |
| performance                           |
| review                                |
| software                              |
| standard                              |
| video                                 |

**Comment by larsgw** [comment]
Thanks for the lists. I think I have a few of those implemented already in master (ed568c060b40c270db1c9f5f3bf7455748f63a9d), but they aren't released yet. I'll do the rest after I finish the current development thing, to avoid complicated merge conflicts. It should be finished somewhere this week.

**Comment by avgurf** [comment]
Hey 👋 
I'm not sure if thats supported or not, i am trying to extract an extended bibtex (for example this bibTex file: 

> @article{10.1093/clinids/22.1.91,
>     author = {Ikähelmo, Risto and Siitonen, Anja and Heiskanen, Tarja and Kärkkäinen, Ulla and Kuosmanen, Pauli and Lipponen, Pertti and Mäkelä, P. Helena },
>     title = "{Recurrence of Urinary Tract Infection in a Primary Care Setting: Analysis of a I-Year Follow-up of 179 Women}",
>     journal = {Clinical Infectious Diseases},
>     volume = {22},
>     number = {1},
>     pages = {91-99},
>     year = {1996},
>     month = {01},
>     abstract = "{....}",
>     issn = {1058-4838},
>     doi = {10.1093/clinids/22.1.91},
>     url = {https://doi.org/10.1093/clinids/22.1.91},
>     eprint = {http://oup.prod.sis.lan/cid/article-pdf/22/1/91/810788/22-1-91.pdf},
> }
> 

will result in the following JSON:

>     {
>         "author": [
>             {
>                 "given": "Risto",
>                 "family": "Ikähelmo"
>             },
>             {
>                 "given": "Anja",
>                 "family": "Siitonen"
>             },
>             {
>                 "given": "Tarja",
>                 "family": "Heiskanen"
>             },
>             {
>                 "given": "Ulla",
>                 "family": "Kärkkäinen"
>             },
>             {
>                 "given": "Pauli",
>                 "family": "Kuosmanen"
>             },
>             {
>                 "given": "Pertti",
>                 "family": "Lipponen"
>             },
>             {
>                 "given": "P. Helena",
>                 "family": "Mäkelä"
>             }
>         ],
>         "title": "Recurrence of Urinary Tract Infection in a Primary Care Setting: Analysis of a I-Year Follow-up of 179 Women",
>         "container-title": "Clinical Infectious Diseases",
>         "volume": "22",
>         "issue": "1",
>         "page": "91-99",
>         "ISSN": "1058-4838",
>         "DOI": "10.1093/clinids/22.1.91",
>         "URL": "https://doi.org/10.1093/clinids/22.1.91",
>         "type": "article-journal",
>         "citation-label": "10.1093/clinids/22.1.91",
>         "id": "10.1093/clinids/22.1.91",
>         "issued": {
>             "date-parts": [
>                 [
>                     "1996",
>                     "01"
>                 ]
>             ]
>         },
>         ]
>     }
> 

Is there a way to parse and save the abstract?

**Comment by larsgw** [comment]
This issue should be fixed in v0.5.0-alpha.10. If not, please re-open the issue.
